version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb+srv://chjunior:pass123word@carlos-so2.hwqetps.mongodb.net/carlos-so2?retryWrites=true&w=majority&appName=carlos-so2
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

